### ISSUE TITLE
server encountered an unexpected error while running topgainers.py

### ISSUE THREAD

**Issue by praveenskit** [manishambashta/nseindia#1]
Hi 
While running topgainers.py , encountered this error with python 2.7

topgainererror.log content is showing like this.

{"message": "Error 111 connecting to 127.0.0.1:6379. Connection refused.", "method": "getData"}
{"message": "Error 111 connecting to 127.0.0.1:6379. Connection refused.", "method": "getData"}
{"message": "Error 111 connecting to 127.0.0.1:6379. Connection refused.", "method": "getData"}
{"message": "Error 111 connecting to 127.0.0.1:6379. Connection refused.", "method": "getData"}
{"message": "Error 111 connecting to 127.0.0.1:6379. Connection refused.", "method": "getData"}

{"message": "Error 111 connecting to 127.0.0.1:6379. Connection refused.", "method": "getData"}

Browser error message 

500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/lib/python2.7/site-packages/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "topgainers.py", line 14, in index
    self.createView()
  File "topgainers.py", line 66, in createView
    </div>''' % (self.nsedata["top_"+str(i)]["symbol"],self.nsedata["top_"+str(i)]["ltp"],self.nsedata["top_"+str(i)]["netPrice"],self.nsedata["top_"+str(i)]["tradedQuantity"],self.nsedata["top_"+str(i)]["turnoverInLakhs"],self.nsedata["top_"+str(i)]["openPrice"],self.nsedata["top_"+str(i)]["highPrice"],self.nsedata["top_"+str(i)]["lowPrice"],self.nsedata["top_"+str(i)]["previousPrice"],self.nsedata["top_"+str(i)]["lastCorpAnnouncementDate"],count)
KeyError: 'top_1'

Best Regards
PraveenS

**Comment by praveenskit** [comment]
console output is a follows

[04/Feb/2017:17:06:45] ENGINE Listening for SIGHUP.
[04/Feb/2017:17:06:45] ENGINE Listening for SIGTERM.
[04/Feb/2017:17:06:45] ENGINE Listening for SIGUSR1.
[04/Feb/2017:17:06:45] ENGINE Bus STARTING
[04/Feb/2017:17:06:45] ENGINE Started monitor thread 'Autoreloader'.
[04/Feb/2017:17:06:45] ENGINE Started monitor thread '_TimeoutMonitor'.
[04/Feb/2017:17:06:45] ENGINE Serving on http://0.0.0.0:8080
[04/Feb/2017:17:06:45] ENGINE Bus STARTED
	[04/Feb/2017:17:07:46] HTTP 
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 670, in respond
